pipeline {
    agent any
    parameters {
        string(name: 'NOM', description: 'Veuillez indiquer votre nom')
        string(name: 'PRENOM', description: 'Veuillez indiquer votre prénom')
        password(name: 'SONAR_SERVER_PWD', description: 'Entrer votre mot de passe SONAR')
    
        // Paramètre pour choisir le(s) mois
        string(name: 'MOIS', description: 'Choisissez le(s) mois', defaultValue: 'Janvier', trim: false, multiSelect: true, 
               choiceType: 'PT_MULTI_SELECT', choices: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'])
    
        // Paramètre étendu pour choisir le challenge réaliser pour ce mois
        extendedChoice(name: 'CHALLENGES', description: 'Choisissez le challenge du mois', multiSelectDelimiter: ',', 
                       type: 'PT_MULTI_SELECT', value: '',
                       groovyScript: """
                           return [
                               'Janvier | Commencer à écrire un journal',
                               'Février | Faire de votre maison un espace agréable',
                               'Février | Déconnecter du reste du monde et où faire son nid',
                               'Mars | Méditer avoir plus de temps pour soi',
                               'Mars | Mieux manger',
                               'Mars | Faire plus d\'exercice',
                               'Mars | Arrêter de fumer',
                               'Avril | Faire des petits gestes',
                               'Avril | Dire des paroles aimables',
                               'Mai | Prenez des cours de salsa',
                               'Mai | Inscrivez-vous à un marathon',
                               'Juin | Sortir dîner',
                               'Juin | Passer du temps avec les vôtres',
                               'Juillet | Profiter des grandes vacances',
                               'Juillet | Profiter des festivals',
                               'Août | Prendre une couverture',
                               'Septembre | Explorez de nouveaux terrains',
                               'Septembre | Sortir de sa zone de confort',
                               'Octobre | Savoir se recycler',
                               'Octobre | Acquérir de nouvelles connaissances',
                               'Novembre | Apprendre un nouvel instrument',
                               'Décembre | Faire une prise de conscience sur comment respirer d\'environ 5min par jour'
                           ]
                       """
        )
}

    /* voici un exemple de stage --- courage */
    stages {
        stage('Janvier') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Janvier" && today == '1') {
                        challenges = "Commencer a ecrire un journal"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Janvier" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Fevrier') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Fevrier" && today == '1') {
                        challenges = "Faire de votre maison un espace agreable, Deconnecter du reste du monde et ou faire son nid"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Fevrier" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Mars') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Fevrier" && today == '1') {
                        challenges = "Mediter avoir plus de temps pour soi, Mieux manger, Faire plus d'exercice, Arreter de fumer"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Fevrier" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Avril') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Avril" && today == '1') {
                        challenges = "Faire des petits gestes, Dire des paroles aimables"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Avril" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Mai') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Mai" && today == '1') {
                        challenges = "Prenez des cours de salsa, Inscrivez-vous a un marathon"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Mai" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Juin') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Juin" && today == '1') {
                        challenges = "Sortir diner, Passer du temps avec les votres"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Juin" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Juillet') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Juillet" && today == '1') {
                        challenges = "Profiter des grandes vacances, Profiter des festivals"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Juillet" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Aout') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Aout" && today == '1') {
                        challenges = "Prendre une couverture"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Aout" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Septembre') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Septembre" && today == '1') {
                        challenges = "Prendre une couverture"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Septembre" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Octobre') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Octobre" && today == '1') {
                        challenges = "Savoir se recycler, Acquerir de nouvelles connaissances"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Octobre" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Novembre') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Novembre" && today == '1') {
                        challenges = "Apprendre un nouvel instrument"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Novembre" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Decembre') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Decembre" && today == '1') {
                        challenges = "Faire une prise de conscience sur comment respirer d'environ 5min par jour"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Decembre" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        /* on peut utiliser ou faire un Skip si la condition est remplie */
        stage('TEST') {
            steps {
                script {
                    if (params.SKIP_TEST) {
                        echo 'Skipping tests...'
                    } else {
                        echo 'Testing app...'
                        echo 'Test OK!'
                        /* Fin de l'action  Skip */
                        /* A vous de terminer ce super script ----- Bon courage */
                    }
                }
            }
        }
    }
}
