/* Exemple pour vous aider a realiser vos souhaits enfin votre super projet */
pipeline {
    agent any
    parameters { 
        string(name: 'NOM', description: 'Veuillez indiquer votre nom')
        string(name: 'PRENOM', description: 'Veuillez indiquer votre prenom')
        password(name: 'SONAR_SERVER_PWD', description: 'Entrer votre mot de passe SONAR')
        choice(name: 'MOIS', choices: ['Janvier', 'Fevrier', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet','Aout', 'Septembre', 'Octobre','Novembre', 'Decembre'], description: 'Choisissez le mois')
        choice(name: 'DATE_DU_JOUR', choices: ['1', '2', '3', '4', '5', '6', '7','8', '9', '10','11', '12','13', '14', '15', '16', '17', '18', '19','20', '21', '22','23', '24','25','26','27','28','29','30','31'], description: 'Quel est la date du jour ?')
        choice(name: 'CHALLENGES', choices: ["Janvier | Rediger et garder precieusement un journal intime", "Janvier | Prendre du temps pour ecrire", "Fevrier | Bricoler des meubles", "Fevrier | Acheter des plantes", "Fevrier | Faire un grand menage", "Mars | Faire plus d'exercice", "Mars | Faire des activites que l'on aime (balade, cine)", "Mars | Mieux manger", "Mars | Arreter de fumer", "Avril | Faire un don a une association", "Avril | Envoyer un message gentil a sa famille", "Avril | Emmener son/sa conjoint.e au restaurant", "Avril | Rendre un service a quelqu'un", "Mai | Voyager en famille", "Mai | Effectuer un marathon", "Mai | Prendre des cours de danse", "Mai | Faire du saut a l'elastique", "Juin | Proposer un week-end en famille", "Juin | Appeler sa famille", "Juin | Organiser des sorties entre amis", "Juin | Aller diner", "Juillet | Aller a un concert/festival/boite de nuit", "Juillet | Danser", "Juillet | Faire une fete a la maison", "Juillet | Chanter sa musique preferee", "Aout | Passer une soiree sur la plage", "Aout | Contempler les etoiles", "Aout | Bronzer sous le soleil", "Septembre | Faire de la Via Ferrata", "Septembre | Voyager", "Septembre | Partir a l'aventure", "Septembre | Faire de la randonnee", "Octobre | Apprendre une nouvelle langue", "Octobre | Se former et passer des certifications", "Octobre | Faire des recherches", "Novembre | Faire du solfege", "Novembre | Chanter", "Novembre | Jouer a un instrument", "Novembre | Apprendre des chansons", "Decembre | Faire de la sophrologie", "Decembre | Participer aux fetes de fins d'annees avec ceux qu'on aime", "Decembre | Aller au ski"], description: 'Entrer les challenge du mois que vous souahitez faire : ')
    }

    /* voici un exemple de stage --- courage */
    stage('Janvier') {
        steps {
            script {
                def challenges = "${params.CHALLENGES}"
                def today = "${params.DATE_DU_JOUR}"
                def mois = "${params.MOIS}"

                if (mois == "Janvier" && today == '1') {
                    challenges = "Prendre du temps pour écrire, Rédiger et garder précieusement un journal intime"
                    echo "Bienvenue au mois de $mois"
                    echo "Voici les challenges possibles : $challenges"
                    sleep 10
                } else if (mois == "Janvier" && today > '1' && today <= '20') {
                    echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                    sleep 10
                }
            }
        }
    }

    /* on peut utiliser ou faire un Skip si la condition est remplie */
    stage('TEST') {
        steps {
            script{
                if (params.SKIP_TEST) {
                    echo 'Skipping tests...'
                } else {
                    echo 'Testing app...'
                    echo 'Test OK!'
                    /* Fin de l'action  Skip */
                    /* A vous de terminer ce super script ----- Bon courage */
                }
            }
        }
    }
}
