pipeline {
    agent any
    parameters {
        string(name: "NOM", description:'Entrez votre nom')
        string(name: "PRENOM", description:'Entrez votre prénom')
        password(name: "Projet_DevOps", description:'Entrer un mot de passe')
    }
    
    stages {
        stage('Exécuter le script Python') {
            steps {
                script {
                    // Afficher les paramètres
                    echo "Nom: ${params.NOM}"
                    echo "Prénom: ${params.PRENOM}"
                    echo "Mot de passe: ${params.Projet_DevOps}"

                    // Lire le contenu du fichier Python depuis le même répertoire
                    def codePython = readFile 'script.py'

                    // Exécuter le code Python
                    def result = bat(script: "python -c \"${codePython}\"", returnStatus: true)

                    // Afficher la sortie de l'exécution
                    echo "Résultat de l'exécution du script : ${result}"
                }
            }
        }
    }
}
