pipeline {
    agent any
    parameters {
        string(name: "NOM", description:'Entrez votre nom')
        string(name: "PRENOM", description:'Entrez votre prénom')
        password(name: "Projet_DevOps", description:'Entrer un mot de passe')
    }
    
    stages {
        stage('Exécuter le script Python') {
            steps {
                script {
                    // Afficher les paramètres
                    echo "Nom: ${params.NOM}"
                    echo "Prénom: ${params.PRENOM}"
                    echo "Mot de passe: ${params.Projet_DevOps}"

                    // Lire le contenu du fichier Python depuis le même répertoire
                    def codePython = readFile 'date.py'
                    
                    // Afficher le contenu du fichier Python
                    echo "Contenu du fichier Python : ${codePython}"

                    // Écrire le code Python dans un fichier temporaire
                    def tempFile = File.createTempFile('temp_script', '.py')
                    tempFile.text = codePython

                    // Exécuter le code Python à partir du fichier temporaire
                    def result = bat(script: "python ${tempFile} 2>&1", returnStatus: true)

                    // Afficher la sortie de l'exécution
                    echo "Résultat de l'exécution du script : ${result}"
                }
            }
        }
    }
}
