pipeline {
    agent any
    parameters {
        string(name: "NOM", description: 'Entrez votre nom')
        string(name: "PRENOM", description: 'Entrez votre prénom')
        password(name: "Projet_DevOps", description: 'Entrer un mot de passe')
        string(name: 'CHALLENGES', defaultValue: '', description: 'Sélectionnez les challenges du mois que vous souhaitez faire (séparés par des virgules)', trim: true)
    }
    stages {
        stage('Afficher les paramètres') {
            steps {
                echo "Nom: ${params.NOM}"
                echo "Prénom: ${params.PRENOM}"
                echo "Mot de passe: ${params.Projet_DevOps}"
                echo "Challenges : ${params.CHALLENGES}"
            }
        }

        stage('Exécuter le script Python') {
            steps {
                script {
                    // Convertir la liste de challenges en tableau
                    def selectedChallenges = params.CHALLENGES.split(',')

                    // Exécuter le code Python à partir du fichier date.py avec les challenges sélectionnés
                    def result = bat(script: "python date.py ${selectedChallenges.join(' ')} 2>&1", returnStatus: true)

                    // Afficher la sortie de l'exécution
                    echo "Résultat de l'exécution du script : ${result}"
                }
            }
        }
    }
}
