pipeline {
    agent any
    parameters {
        string(name: "NOM", description: 'Entrez votre nom')
        string(name: "PRENOM", description: 'Entrez votre prénom')
        password(name: "Projet_DevOps", description: 'Entrer un mot de passe')
        extendedChoice(
            name: 'CHALLENGES',
            description: 'Sélectionnez les challenges du mois que vous souhaitez faire :',
            multiSelectDelimiter: ',',
            type: 'PT_MULTI_SELECT',
            value: '',
            groovyScript: """
                return [
                    "Janvier | Commencer à écrire un journal",
                    "Fevrier | Faire de votre maison un espace agréable",
                    "Fevrier | Déconnecter du reste du monde et où faire son nid",
                    "Mars | Méditer avoir plus de temps pour soi",
                    "Mars | Mieux manger",
                    "Mars | Faire plus d'exercice",
                    "Mars | Arrêter de fumer",
                    "Avril | Faire des petits gestes",
                    "Avril | Dire des paroles aimables",
                    "Mai | Prenez des cours de salsa",
                    "Mai | Inscrivez-vous à un marathon",
                    "Juin | Sortir dîner",
                    "Juin | Passer du temps avec les vôtres",
                    "Juillet | Profiter des grandes vacances",
                    "Juillet | Profiter des festivals",
                    "Aout | Prendre une couverture"
                ]
            """
        )
    }
    stages {
        stage('Saisie des informations') {
            steps {
                script {
                    // Saisie des informations
                    def userNom = input(message: 'Entrez votre nom', parameters: [string(defaultValue: '', description: 'Nom', name: 'NOM')])
                    def userPrenom = input(message: 'Entrez votre prénom', parameters: [string(defaultValue: '', description: 'Prénom', name: 'PRENOM')])
                    def userPassword = input(message: 'Entrez un mot de passe', parameters: [password(defaultValue: '', description: 'Mot de passe', name: 'Projet_DevOps')])
                    def selectedChallenges = input(message: 'Sélectionnez les challenges du mois que vous souhaitez faire', parameters: [extendedChoice(defaultValue: '', description: 'Challenges', name: 'CHALLENGES', type: 'PT_MULTI_SELECT', value: '', groovyScript: """
                        return [
                            "Janvier | Commencer à écrire un journal",
                            "Fevrier | Faire de votre maison un espace agréable",
                            "Fevrier | Déconnecter du reste du monde et où faire son nid",
                            "Mars | Méditer avoir plus de temps pour soi",
                            "Mars | Mieux manger",
                            "Mars | Faire plus d'exercice",
                            "Mars | Arrêter de fumer",
                            "Avril | Faire des petits gestes",
                            "Avril | Dire des paroles aimables",
                            "Mai | Prenez des cours de salsa",
                            "Mai | Inscrivez-vous à un marathon",
                            "Juin | Sortir dîner",
                            "Juin | Passer du temps avec les vôtres",
                            "Juillet | Profiter des grandes vacances",
                            "Juillet | Profiter des festivals",
                            "Aout | Prendre une couverture"
                        ]
                    """)])

                    // Afficher les informations saisies
                    echo "Nom: ${userNom}"
                    echo "Prénom: ${userPrenom}"
                    echo "Mot de passe: ${userPassword}"
                    echo "Challenges : ${selectedChallenges}"

                    // Compter le nombre de challenges sélectionnés
                    def countChallenges = selectedChallenges.split(',').size()

                    // Exécuter le script Python avec le nombre de challenges sélectionnés
                    def result = bat(script: "python date.py ${countChallenges}", returnStatus: true)

                    // Afficher la sortie de l'exécution
                    echo "Résultat de l'exécution du script : ${result}"
                }
            }
        }
    }
}
