pipeline:
  agent: any
  parameters:
    - string:
        name: "NOM"
        description: "Entrez votre nom"
    - string:
        name: "PRENOM"
        description: "Entrez votre prénom"
    - password:
        name: "Projet_DevOps"
        description: "Entrer un mot de passe"
    - yaml:
        name: "CHALLENGES"
        default: ["Janvier | Commencer à écrir un journal"]
        description: 'Sélectionnez les challenges du mois que vous souhaitez faire : '
        choices:
          - "Janvier | Commencer à écrir un journal"
          - "Fevrier | Faire de votre maison un espace agréable"
          - "Fevrier | Déconnecter du reste du monde et où faire son nid"
          - "Mars | Méditer avoir plus de temps pour soi"
          - "Mars | Mieux manger"
          - "Mars | Faire plus d'exercice"
          - "Mars | Arrêter de fumer"
          - "Avril | Faire des petits gestes"
          - "Avril | Dire des paroles aimables"
          - "Mai | Prenez des cours de salsa"
          - "Mai | Inscrivez-vous à un marathon"
          - "Juin | Sortir dîner"
          - "Juin | Passer du temps avec les vôtres"
          - "Juillet | Profiter des grandes vacances"
          - "Juillet | Profiter des festivals"
          - "Aout | Prendre une couverture"
        multiSelectDelimiter: ","
  stages:
    - stage: "Afficher les paramètres"
      steps:
        - script:
            name: "Afficher les paramètres"
            code: |
              echo "Nom: \${NOM}"
              echo "Prénom: \${PRENOM}"
              echo "Mot de passe: \${Projet_DevOps}"
              echo "Challenges : \${CHALLENGES}"
    - stage: "Exécuter le script Python"
      steps:
        - script:
            name: "Exécuter le script Python"
            code: |
              // Exécuter le code Python à partir du fichier date.py
              def result = bat(script: "python date.py 2>&1", returnStatus: true)
              // Afficher la sortie de l'exécution
              echo "Résultat de l'exécution du script : \${result}"
