pipeline {
    agent any
    parameters {
        string(name: 'NOM', description: 'Veuillez indiquer votre nom')
        string(name: 'PRENOM', description: 'Veuillez indiquer votre prénom')
        password(name: 'SONAR_SERVER_PWD', description: 'Entrer votre mot de passe SONAR')
        
        // Paramètre de sélection pour le mois
        choice(
        name: 'MOIS',
        choices: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
        description: 'Choisissez le mois'
        )

        //Choix de la date
         choice(name: 'DATE_DU_JOUR', 
         choices: ['1', '2', '3', '4', '5', '6', '7','8', '9', '10','11', '12','13', '14', '15', '16', '17', '18', '19','20', '21', '22','23', '24','25','26','27','28','29','30','31'], 
         description: 'Quel est la date du jour ?')
        
        // Paramètre de sélection multiple pour les challenges
        extendedChoice(
            name: 'CHALLENGES',
            description: 'Choisissez le(s) challenge(s) pour ce mois',
            multiSelectDelimiter: ',',
            type: 'PT_MULTI_SELECT',
            groovyScript: """
                return[
                "Janvier | Commencer a ecrire un journal",
                "Fevrier | Faire de votre maison un espace agreable",
                "Fevrier | Deconnecter du reste du monde et ou faire son nid",
                "Mars | Mediter avoir plus de temps pour soi",
                "Mars | Mieux manger",
                "Mars | Faire plus d'exercice",
                "Mars | Arreter de fumer",
                "Avril | Faire des petits gestes",
                "Avril | Dire des paroles aimables",
                "Mai | Prenez des cours de salsa",
                "Mai | Inscrivez-vous a un marathon",
                "Juin | Sortir diner",
                "Juin | Passer du temps avec les votres",
                "Juillet | Profiter des grandes vacances",
                "Juillet | Profiter des festivals",
                "Aout | Prendre une couverture",
                "Septembre | Explorez de nouveaux terrains",
                "Septembre | Sortir de sa zone de confort",
                "Octobre | Savoir se recycler",
                "Octobre | Acquerir de nouvelles connaissances",
                "Novembre | Apprendre un nouvel instrument",
                "Decembre | Faire une prise de conscience sur comment respirer d'environ 5min par jour"]
            """
        )

    }


    /* voici un exemple de stage --- courage */
    stages {
        stage('Set Parameters') {
            steps {
                script {
                    // Obtenez le mois actuel
                    def currentMonth = "${params.MOIS}"

                    // Déterminez si le mois actuel correspond à celui spécifié dans le paramètre
                    def runJanvier = currentMonth == params.MOIS

                    // Affichez les informations pour le débogage (peut être retiré dans une version de production)
                    echo "Mois actuel: ${currentMonth}"
                    echo "Exécuter Janvier? ${runJanvier}"

                    // Définissez le paramètre RUN_JANVIER en conséquence
                    if (params.MOIS == 'Janvier') {
                        booleanParam(name: 'RUN_JANVIER', defaultValue: runJanvier, description: 'Exécuter l\'étape Janvier')
                    } else {
                        booleanParam(name: 'RUN_JANVIER', defaultValue: false, description: 'Exécuter l\'étape Janvier')
                    }
                }
            }
        }
        stage('Janvier') {
            steps {
                script {
                    // Obtenir les valeurs des paramètres
                    def challenges = "${params.CHALLENGES}".tokenize(',').size()
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"
    
                    // Vérifier si la valeur de challenges est égale à la constante
                    if (challenges == 1) {
                        echo "Un seul challenge du mois de $mois est réalisé."
                    } else if (challenges < 1 && mois == "Janvier" && today == '1') {
                        challenges = "Commencer a ecrire un journal"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (challenges == 0 && mois == "Janvier" && today > '1' && today <= '20') {
                        echo "Bienvenue au mois de $mois"
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Fevrier') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}".tokenize(',').size()
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    // Vérifier si la valeur de challenges est égale à la constante
                    if (challenges == 2) {
                        echo "Tout les challenge du mois de $mois est réalisé."
                    } else if (challenges < 2 && mois == "Fevrier" && today == '1') {
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (challenges < 2 && mois == "Janvier" && today > '1' && today <= '20') {
                        echo "Bienvenue au mois de $mois"
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Mars') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Mars" && today == '1') {
                        challenges = "Mediter avoir plus de temps pour soi, Mieux manger, Faire plus d'exercice, Arreter de fumer"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Mars" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Avril') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Avril" && today == '1') {
                        challenges = "Faire des petits gestes, Dire des paroles aimables"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Avril" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Mai') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Mai" && today == '1') {
                        challenges = "Prenez des cours de salsa, Inscrivez-vous a un marathon"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Mai" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Juin') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Juin" && today == '1') {
                        challenges = "Sortir diner, Passer du temps avec les votres"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Juin" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Juillet') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Juillet" && today == '1') {
                        challenges = "Profiter des grandes vacances, Profiter des festivals"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Juillet" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Aout') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Aout" && today == '1') {
                        challenges = "Prendre une couverture"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Aout" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Septembre') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Septembre" && today == '1') {
                        challenges = "Prendre une couverture"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Septembre" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Octobre') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Octobre" && today == '1') {
                        challenges = "Savoir se recycler, Acquerir de nouvelles connaissances"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Octobre" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Novembre') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Novembre" && today == '1') {
                        challenges = "Apprendre un nouvel instrument"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Novembre" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        stage('Decembre') {
            steps {
                script {
                    def challenges = "${params.CHALLENGES}"
                    def today = "${params.DATE_DU_JOUR}"
                    def mois = "${params.MOIS}"

                    if (mois == "Decembre" && today == '1') {
                        challenges = "Faire une prise de conscience sur comment respirer d'environ 5min par jour"
                        echo "Bienvenue au mois de $mois"
                        echo "Voici les challenges possibles : $challenges"
                        sleep 10
                    } else if (mois == "Decembre" && today > '1' && today <= '20') {
                        echo "Attention, nous sommes le $today du mois, il ne vous reste plus beaucoup de temps pour faire vos objectifs."
                        sleep 10
                    }
                }
            }
        }
        /* on peut utiliser ou faire un Skip si la condition est remplie */
        stage('TEST') {
            steps {
                script {
                    if (params.SKIP_TEST) {
                        echo 'Skipping tests...'
                    } else {
                        echo 'Testing app...'
                        echo 'Test OK!'
                        /* Fin de l'action  Skip */
                        /* A vous de terminer ce super script ----- Bon courage */
                    }
                }
            }
        }
    }
}
