pipeline {
    agent any
    parameters {
        string(name: "NOM", description: 'Entrez votre nom')
        string(name: "PRENOM", description: 'Entrez votre prénom')
        password(name: "Projet_DevOps", description: 'Entrer un mot de passe')
        extendedChoice(
            name: 'CHALLENGES',
            description: 'Sélectionnez les challenges du mois que vous souhaitez faire :',
            multiSelectDelimiter: ',',
            type: 'PT_MULTI_SELECT',
            value: '',
            groovyScript: """
                return [
                "Janvier | Commencer a ecrire un journal",
                "Fevrier | Faire de votre maison un espace agreable",
                "Fevrier | Deconnecter du reste du monde et ou faire son nid",
                "Mars | Mediter avoir plus de temps pour soi",
                "Mars | Mieux manger",
                "Mars | Faire plus d'exercice",
                "Mars | Arreter de fumer",
                "Avril | Faire des petits gestes",
                "Avril | Dire des paroles aimables",
                "Mai | Prenez des cours de salsa",
                "Mai | Inscrivez-vous a un marathon",
                "Juin | Sortir diner",
                "Juin | Passer du temps avec les votres",
                "Juillet | Profiter des grandes vacances",
                "Juillet | Profiter des festivals",
                "Aout | Prendre une couverture",
                "Septembre | Explorez de nouveaux terrains",
                "Septembre | Sortir de sa zone de confort",
                "Octobre | Savoir se recycler",
                "Octobre | Acquerir de nouvelles connaissances",
                "Novembre | Apprendre un nouvel instrument",
                "Decembre | Faire une prise de conscience sur comment respirer d'environ 5min par jour"
                ]
            """
        )
    }
    stages {
        stage('Afficher les paramètres') {
            steps {
                echo "Nom: ${params.NOM}"
                echo "Prénom: ${params.PRENOM}"
                echo "Mot de passe: ${params.Projet_DevOps}"
                echo "Challenges : ${params.CHALLENGES}"
            }
        }

        stage('Exécuter le script Python') {
            steps {
                script {
                    // Échapper aux guillemets doubles dans les challenges sélectionnés
                    def escapedChallenges = params.CHALLENGES.replaceAll('"', '\\"')

                    // Exécuter le code Python à partir du fichier date.py avec les challenges sélectionnés
                    def result = bat(script: """python date.py "${escapedChallenges}" """, returnStatus: true)
                    // Afficher la sortie de l'exécution
                    echo "Résultat de l'exécution du script : ${result}"
                }
            }
        }
    }
}
