// ...

stage('Exécuter le script Python de comptage') {
    steps {
        script {
            // Exécuter le script Python pour compter les challenges sélectionnés
            def countResult = bat(script: "python count_challenges.py \"${params.CHALLENGES}\"", returnStatus: true)

            // Afficher la sortie de l'exécution
            echo "Résultat de l'exécution du script de comptage : ${countResult}"

            // Vérifier la date et le nombre de challenges
            checkDateAndChallenges(params.CHALLENGES, countResult)
        }
    }
}

// Fonction pour vérifier la date et le nombre de challenges
def checkDateAndChallenges(selectedChallenges, countResult) {
    // Utilisation de SimpleDateFormat
    def currentDate = new Date()
    def targetDate = new SimpleDateFormat("yyyy-MM-dd").parse("2024-01-17")

    if (currentDate.after(targetDate)) {
        // Vérifier le résultat du script de comptage
        if (countResult.toInteger() > 8) {
            echo "Dans les temps"
        } else {
            echo "En retard sur les challenges"
        }
    }
}
