pipeline {
    agent any
    parameters {
        string(name: "NOM", description: 'Entrez votre nom')
        string(name: "PRENOM", description: 'Entrez votre prénom')
        password(name: "Projet_DevOps", description: 'Entrer un mot de passe')
        choice(
            name: 'CHALLENGES',
            choices: [
                "Janvier | Commencer à écrire un journal",
                "Fevrier | Faire de votre maison un espace agréable",
                "Fevrier | Déconnecter du reste du monde et où faire son nid",
                // ... Ajoutez d'autres options selon votre besoin
            ],
            description: 'Sélectionnez les challenges du mois que vous souhaitez faire : ',
            multiSelectDelimiter: ','
        )
    }
    stages {
        stage('Afficher les paramètres') {
            steps {
                echo "Nom: ${params.NOM}"
                echo "Prénom: ${params.PRENOM}"
                echo "Mot de passe: ${params.Projet_DevOps}"
                echo "Challenges : ${params.CHALLENGES}"
            }
        }

        stage('Exécuter le script Python') {
            steps {
                script {
                    // Exécuter le code Python à partir du fichier date.py avec les challenges sélectionnés
                    def result = bat(script: "python date.py ${params.CHALLENGES} 2>&1", returnStatus: true)

                    // Afficher la sortie de l'exécution
                    echo "Résultat de l'exécution du script : ${result}"
                }
            }
        }
    }
}
